version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/sb3"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/sb2"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/cypress-test"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
